//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailersApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public int Department_ID { get; set; }
        public int Retailer_ID { get; set; }
        public string Department_Name { get; set; }
        public string Department_Code { get; set; }
        public string image_url { get; set; }
    
        public virtual Retailer Retailer { get; set; }
    }
}
