USE [master]
GO

/****** Object:  Database [RetailDB]    Script Date: 06-Oct-20 2:14:15 PM ******/
DROP DATABASE [RetailDB]
GO

/****** Object:  Database [RetailDB]    Script Date: 06-Oct-20 2:14:16 PM ******/
CREATE DATABASE [RetailDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RetailDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\RetailDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RetailDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\RetailDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [RetailDB] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RetailDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RetailDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RetailDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RetailDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RetailDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RetailDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [RetailDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RetailDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RetailDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RetailDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RetailDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RetailDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RetailDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RetailDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RetailDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RetailDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RetailDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RetailDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RetailDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RetailDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RetailDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RetailDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RetailDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RetailDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [RetailDB] SET  MULTI_USER 
GO

ALTER DATABASE [RetailDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RetailDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RetailDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RetailDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [RetailDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [RetailDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [RetailDB] SET  READ_WRITE 
GO


